# Pymaceuticals Inc.
---

### Analysis

- Add your analysis here.

In [12]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Combine the data into a single DataFrame
#merged_df = study_results.merge(mouse_metadata, on='Mouse ID', how='inner')
#merged_df = study_results.merge(mouse_metadata, on='Mouse ID', how='outer')
merged_df = study_results.merge(mouse_metadata, on='Mouse ID', how='left')
#merged_df = mouse_metadata.merge(study_results, on='Mouse ID', how='inner')
#merged_df = mouse_metadata.merge(study_results, on='Mouse ID', how='outer')
#merged_df = mouse_metadata.merge(study_results, on='Mouse ID', how='left')

# Display the data table for preview
selected_merged_df = merged_df[["Mouse ID", "Timepoint", "Tumor Volume (mm3)", "Metastatic Sites", \
                     "Drug Regimen", "Sex", "Age_months", "Weight (g)"]]

selected_merged_df.head()

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g)
0,b128,0,45.0,0,Capomulin,Female,9,22
1,f932,0,45.0,0,Ketapril,Male,15,29
2,g107,0,45.0,0,Ketapril,Female,2,29
3,a457,0,45.0,0,Ketapril,Female,11,30
4,c819,0,45.0,0,Ketapril,Male,21,25

In [2]:
selected_merged_copy_df = selected_merged_df.copy()

In [ ]:
output_file = 'output.csv'
selected_merged_copy_df.to_csv(output_file, index=False)

In [ ]:
selected_rows1 = selected_merged_df.loc[selected_merged_df["Mouse ID"]=="g989"]
selected_rows1

In [ ]:
# Checking the number of mice.
mouse_count = selected_merged_df["Mouse ID"].nunique()
mouse_count

In [ ]:
duplicates = selected_merged_df[selected_merged_df.duplicated(subset=["Mouse ID", "Timepoint"], keep=False)]
selected_value = duplicates.loc[:,'Mouse ID']
selected_value.unique()

In [ ]:
duplicates

In [ ]:
clean_merged1_df = selected_merged_df.drop_duplicates(subset=['Mouse ID', 'Timepoint'])
clean_merged1_df.head()

In [ ]:
selected_rows2 = clean_merged1_df.loc[clean_merged1_df["Mouse ID"]=="g989"]
selected_rows2

In [ ]:
mouse_count2 = clean_merged1_df["Mouse ID"].nunique()
mouse_count2

In [ ]:
# Our data should be uniquely identified by Mouse ID and Timepoint
# Get the duplicate mice by ID number that shows up for Mouse ID and Timepoint.

In [ ]:
# Optional: Get all the data for the duplicate mouse ID.

In [ ]:
clean_merged2_df = selected_merged_df.drop_duplicates(subset=['Mouse ID', 'Timepoint'], keep='first', inplace=True)
#clean_merged_df = selected_merged_df.drop_duplicates()
#selected_merged_df.drop_duplicates()
clean_merged2_df.head()
#selected_merged_df.head()

In [3]:
clean_merged55_df = selected_merged_copy_df.drop_duplicates(subset=['Mouse ID','Timepoint'])
#clean_merged_df = selected_merged_df.drop_duplicates()
#selected_merged_df.drop_duplicates()
clean_merged55_df
#selected_merged_df.head(

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g)
0,b128,0,45.000000,0,Capomulin,Female,9,22
1,f932,0,45.000000,0,Ketapril,Male,15,29
2,g107,0,45.000000,0,Ketapril,Female,2,29
3,a457,0,45.000000,0,Ketapril,Female,11,30
4,c819,0,45.000000,0,Ketapril,Male,21,25
...,...,...,...,...,...,...,...,...
1888,r944,45,41.581521,2,Capomulin,Male,12,25
1889,u364,45,31.023923,3,Capomulin,Male,18,17
1890,p438,45,61.433892,1,Ceftamin,Female,11,26
1891,x773,45,58.634971,4,Placebo,Female,21,30
1892,b879,45,72.555239,2,Stelasyn,Female,4,26

In [ ]:
mouse_count55 = clean_merged55_df["Mouse ID"].nunique()
mouse_count55

In [ ]:
selected_rows = clean_merged3_df.loc[clean_merged3_df["Mouse ID"]=="g989"]
selected_rows

In [ ]:
#mouse_count3 = clean_merged_df["Mouse ID"].nunique()
mouse_count3 = clean_merged3_df["Mouse ID"].nunique()
mouse_count3

In [ ]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})
df

In [ ]:
df.drop_duplicates()

In [ ]:
# Create a clean DataFrame by dropping the duplicate mouse by its ID.

In [ ]:
# Checking the number of mice in the clean DataFrame.

In [ ]:
clean_merged55_df.head()

In [ ]:
clean_merged55_df.columns

In [17]:
clean_merged55_df_copy = clean_merged55_df.copy()
clean_merged55_df_copy["Tumor_Volume_Copy1"] = clean_merged55_df_copy["Tumor Volume (mm3)"].copy()
clean_merged55_df_copy["Tumor_Volume_Copy2"] = clean_merged55_df_copy["Tumor Volume (mm3)"].copy()
clean_merged55_df_copy["Tumor_Volume_Copy3"] = clean_merged55_df_copy["Tumor Volume (mm3)"].copy()
clean_merged55_df_copy["Tumor_Volume_Copy4"] = clean_merged55_df_copy["Tumor Volume (mm3)"].copy()
clean_merged55_df_copy["Tumor_Volume_Copy5"] = clean_merged55_df_copy["Tumor Volume (mm3)"].copy()
clean_merged55_df_copy

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g),Tumor_Volume_Copy1,Tumor_Volume_Copy2,Tumor_Volume_Copy3,Tumor_Volume_Copy4,Tumor_Volume_Copy5,Tumor_Volume_Copyxx
0,b128,0,45.000000,0,Capomulin,Female,9,22,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
1,f932,0,45.000000,0,Ketapril,Male,15,29,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
2,g107,0,45.000000,0,Ketapril,Female,2,29,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
3,a457,0,45.000000,0,Ketapril,Female,11,30,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
4,c819,0,45.000000,0,Ketapril,Male,21,25,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,r944,45,41.581521,2,Capomulin,Male,12,25,41.581521,41.581521,41.581521,41.581521,41.581521,41.581521
1889,u364,45,31.023923,3,Capomulin,Male,18,17,31.023923,31.023923,31.023923,31.023923,31.023923,31.023923
1890,p438,45,61.433892,1,Ceftamin,Female,11,26,61.433892,61.433892,61.433892,61.433892,61.433892,61.433892
1891,x773,45,58.634971,4,Placebo,Female,21,30,58.634971,58.634971,58.634971,58.634971,58.634971,58.634971
1892,b879,45,72.555239,2,Stelasyn,Female,4,26,72.555239,72.555239,72.555239,72.555239,72.555239,72.555239

In [9]:
#clean_merged55_df.loc[:, "Tumor Volume_copy1"] = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()

Tumor_Volume_Copy1 = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()
Tumor_Volume_Copy2 = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()
Tumor_Volume_Copy3 = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()
Tumor_Volume_Copy4 = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()
Tumor_Volume_Copy5 = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()
#Tumor Volume Copy4 = clean_merged55_df.loc[:, "Tumor Volume (mm3)"].copy()
Tumor_Volume_Copy1

0       45.000000
1       45.000000
2       45.000000
3       45.000000
4       45.000000
          ...
1888    41.581521
1889    31.023923
1890    61.433892
1891    58.634971
1892    72.555239
Name: Tumor Volume (mm3), Length: 1888, dtype: float64

In [10]:
clean_merged55_df["Tumor_Volume_Copy1"]=Tumor_Volume_Copy1
clean_merged55_df["Tumor_Volume_Copy2"]=Tumor_Volume_Copy2
clean_merged55_df["Tumor_Volume_Copy3"]=Tumor_Volume_Copy3
clean_merged55_df["Tumor_Volume_Copy4"]=Tumor_Volume_Copy4
clean_merged55_df["Tumor_Volume_Copy5"]=Tumor_Volume_Copy5
clean_merged55_df

C:\Users\GPEL_HPENVY\AppData\Local\Temp\ipykernel_25096\3539209572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_merged55_df["Tumor_Volume_Copy1"]=Tumor_Volume_Copy1
C:\Users\GPEL_HPENVY\AppData\Local\Temp\ipykernel_25096\3539209572.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_merged55_df["Tumor_Volume_Copy2"]=Tumor_Volume_Copy2
C:\Users\GPEL_HPENVY\AppData\Local\Temp\ipykernel_25096\3539209572.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_merged55_df["Tumor_Volume_Copy3"]=Tumor_Volume_Copy3
C:\Users\GPEL_HPENVY\AppData\Local\Temp\ipykernel_25096\3539209572.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_merged55_df["Tumor_Volume_Copy4"]=Tumor_Volume_Copy4
C:\Users\GPEL_HPENVY\AppData\Local\Temp\ipykernel_25096\3539209572.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_merged55_df["Tumor_Volume_Copy5"]=Tumor_Volume_Copy5

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g),Tumor_Volume_Copy1,Tumor_Volume_Copy2,Tumor_Volume_Copy3,Tumor_Volume_Copy4,Tumor_Volume_Copy5
0,b128,0,45.000000,0,Capomulin,Female,9,22,45.000000,45.000000,45.000000,45.000000,45.000000
1,f932,0,45.000000,0,Ketapril,Male,15,29,45.000000,45.000000,45.000000,45.000000,45.000000
2,g107,0,45.000000,0,Ketapril,Female,2,29,45.000000,45.000000,45.000000,45.000000,45.000000
3,a457,0,45.000000,0,Ketapril,Female,11,30,45.000000,45.000000,45.000000,45.000000,45.000000
4,c819,0,45.000000,0,Ketapril,Male,21,25,45.000000,45.000000,45.000000,45.000000,45.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,r944,45,41.581521,2,Capomulin,Male,12,25,41.581521,41.581521,41.581521,41.581521,41.581521
1889,u364,45,31.023923,3,Capomulin,Male,18,17,31.023923,31.023923,31.023923,31.023923,31.023923
1890,p438,45,61.433892,1,Ceftamin,Female,11,26,61.433892,61.433892,61.433892,61.433892,61.433892
1891,x773,45,58.634971,4,Placebo,Female,21,30,58.634971,58.634971,58.634971,58.634971,58.634971
1892,b879,45,72.555239,2,Stelasyn,Female,4,26,72.555239,72.555239,72.555239,72.555239,72.555239

## Summary Statistics

In [24]:
#clean_merged55_df.loc[:, "Tumor Volume_copy1"] = clean_merged55_df["Tumor Volume (mm3)"].copy()
#clean_merged55_df.head()
# clean_merged55_df["Tumor Volume_copy2"] = clean_merged55_df["Tumor Volume (mm3)"].copy()
# clean_merged55_df["Tumor Volume_copy3"] = clean_merged55_df["Tumor Volume (mm3)"].copy()

grouped_df = clean_merged55_df_copy.groupby('Drug Regimen').agg({
     'Tumor_Volume_Copy1': 'mean',                                               # get the first mention since the data is repeated
     'Tumor_Volume_Copy2': 'median',                                               # get the first mention since the data is repeated
     'Tumor_Volume_Copy3': 'var',                                               # get the first mention since the data is repeated
     'Tumor_Volume_Copy4': 'std',                                                # get the mean for "maths_score2"
     'Tumor_Volume_Copy5': 'sem'       # get the mean in percentage for "maths_score"
#    'Tumor_Volume_Copy5': lambda x: np.std(x) / np.sqrt(len(x))       # get the mean in percentage for "maths_score"
 }).reset_index()  

# Rename columns per required output
grouped_df.rename(columns={
    'Tumor_Volume_Copy1': 'Mean Tumor Volume',
    'Tumor_Volume_Copy2': 'Median Tumor Volume',
    'Tumor_Volume_Copy3': 'Tumor Volume Variance',
    'Tumor_Volume_Copy4': 'Tumor Volume Std. Dev.',
    'Tumor_Volume_Copy5': 'Tumor Volume Std. Err.'
}, inplace=True)  

grouped_df.set_index('Drug Regimen', inplace=True)              # use 'School_Name' as index
#grouped_df.rename_axis(None, inplace=True)   

grouped_df

,Mean Tumor Volume,Median Tumor Volume,Tumor Volume Variance,Tumor Volume Std. Dev.,Tumor Volume Std. Err.
Drug Regimen,,,,,
Capomulin,40.675741,41.557809,24.947764,4.994774,0.329346
Ceftamin,52.591172,51.776157,39.290177,6.268188,0.469821
Infubinol,52.884795,51.820584,43.128684,6.567243,0.492236
Ketapril,55.235638,53.698743,68.553577,8.279709,0.603860
Naftisol,54.331565,52.509285,66.173479,8.134708,0.596466
Placebo,54.033581,52.288934,61.168083,7.821003,0.581331
Propriva,52.393463,50.909965,43.138803,6.568014,0.525862
Ramicane,40.216745,40.673236,23.486704,4.846308,0.320955
Stelasyn,54.233149,52.431737,59.450562,7.710419,0.573111
Zoniferol,53.236507,51.818479,48.533355,6.966589,0.516398

In [ ]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen

# Use groupby and summary statistical methods to calculate the following properties of each drug regimen: 
# mean, median, variance, standard deviation, and SEM of the tumor volume. 
# Assemble the resulting series into a single summary DataFrame.

In [28]:
result = clean_merged55_df_copy.groupby("Drug Regimen")["Tumor Volume (mm3)"].agg(
    mean="mean",
    median="median",
    var="var",
    std="std",
    sem="sem"
)

# Reset the index to match the desired output format
result = result.reset_index()
result.set_index('Drug Regimen', inplace=True) 

result.columns = pd.MultiIndex.from_tuples([
    ("Tumor Volume (mm3)", "mean"),
    ("Tumor Volume (mm3)", "median"),
    ("Tumor Volume (mm3)", "var"),
    ("Tumor Volume (mm3)", "std"),
    ("Tumor Volume (mm3)", "sem")
])

#result.set_index('Drug Regimen', inplace=True) 
result

             Tumor Volume (mm3)
                           mean     median        var       std       sem
Drug Regimen
Capomulin             40.675741  41.557809  24.947764  4.994774  0.329346
Ceftamin              52.591172  51.776157  39.290177  6.268188  0.469821
Infubinol             52.884795  51.820584  43.128684  6.567243  0.492236
Ketapril              55.235638  53.698743  68.553577  8.279709  0.603860
Naftisol              54.331565  52.509285  66.173479  8.134708  0.596466
Placebo               54.033581  52.288934  61.168083  7.821003  0.581331
Propriva              52.393463  50.909965  43.138803  6.568014  0.525862
Ramicane              40.216745  40.673236  23.486704  4.846308  0.320955
Stelasyn              54.233149  52.431737  59.450562  7.710419  0.573111
Zoniferol             53.236507  51.818479  48.533355  6.966589  0.516398

In [ ]:
# A more advanced method to generate a summary statistics table of mean, median, variance, standard deviation,
# and SEM of the tumor volume for each regimen (only one method is required in the solution)

# Using the aggregation method, produce the same summary statistics in a single line

## Bar and Pie Charts

In [ ]:
# Generate a bar plot showing the total number of rows (Mouse ID/Timepoints) for each drug regimen using Pandas.

In [ ]:
# Generate a bar plot showing the total number of rows (Mouse ID/Timepoints) for each drug regimen using pyplot.

In [ ]:
# Generate a pie plot showing the distribution of female versus male mice using Pandas

In [ ]:
# Generate a pie plot showing the distribution of female versus male mice using pyplot

## Quartiles, Outliers and Boxplots

In [ ]:
# Calculate the final tumor volume of each mouse across four of the treatment regimens:  
# Capomulin, Ramicane, Infubinol, and Ceftamin

# Start by getting the last (greatest) timepoint for each mouse


# Merge this group df with the original DataFrame to get the tumor volume at the last timepoint

In [ ]:
# Put treatments into a list for for loop (and later for plot labels)


# Create empty list to fill with tumor vol data (for plotting)


# Calculate the IQR and quantitatively determine if there are any potential outliers. 

    
    # Locate the rows which contain mice on each drug and get the tumor volumes

    
    # add subset 

    
    # Determine outliers using upper and lower bounds

In [ ]:
# Generate a box plot that shows the distrubution of the tumor volume for each treatment group.

## Line and Scatter Plots

In [ ]:
# Generate a line plot of tumor volume vs. time point for a single mouse treated with Capomulin

In [ ]:
# Generate a scatter plot of mouse weight vs. the average observed tumor volume for the entire Capomulin regimen

## Correlation and Regression

In [ ]:
# Calculate the correlation coefficient and a linear regression model 
# for mouse weight and average observed tumor volume for the entire Capomulin regimen